config/routes.rb
Loomio::Application.routes.draw do

  get "/groups", to: 'groups/public_groups#index', as: :public_groups

  ActiveAdmin.routes(self)

  devise_for :users, controllers: { sessions: 'users/sessions',
                                    registrations: 'users/registrations' }

  get "/inbox", to: "inbox#index", as: :inbox
  get '/inbox/preferences', to: 'inbox#preferences', as: :inbox_preferences
  put '/inbox/update_preferences', to: 'inbox#update_preferences', as: :update_inbox_preferences
  match '/inbox/mark_as_read', to: 'inbox#mark_as_read', as: :mark_as_read_inbox
  match '/inbox/mark_all_as_read', to: 'inbox#mark_all_as_read', as: :mark_all_as_read_inbox
  match '/inbox/unfollow', to: 'inbox#unfollow', as: :unfollow_inbox


  resources :invitations, only: [:show]

  resources :group_requests, only: [:create, :new] do
    get :verify, on: :member
  end

  match "/request_new_group", to: "group_requests#new", as: :request_new_group

  match "/group_request_confirmation", to: "group_requests#confirmation", as: :group_request_confirmation

  resources :groups, except: [:index, :new] do
    resources :invitations, only: [:index, :destroy, :new, :create], controller: 'groups/invitations'
    resources :memberships, only: [:index, :destroy, :new, :create], controller: 'groups/memberships' do
      member do
       post :make_admin
       post :remove_admin
      end
    end

    get :setup, on: :member, to: 'groups/group_setup#setup'
    put :finish, on: :member, to: 'groups/group_setup#finish'

    post :add_members, on: :member
    post :hide_next_steps, on: :member
    get :add_subgroup, on: :member

    resources :motions
    resources :discussions, only: [:index, :new]
    post :email_members, on: :member
    post :edit_description, on: :member
    post :edit_privacy, on: :member
    delete :leave_group, on: :member
  end

  get 'groups/:group_id/request_membership',   to: 'groups/membership_requests#new',          as: :new_group_membership_request
  post 'groups/:group_id/membership_requests', to: 'groups/membership_requests#create',       as: :group_membership_requests
  delete 'membership_requests/:id/cancel',     to: 'groups/membership_requests#cancel',       as: :cancel_membership_request

  get 'groups/:group_id/membership_requests',  to: 'groups/manage_membership_requests#index', as: :group_membership_requests
  resources :membership_requests, only: [], controller: 'groups/manage_membership_requests' do
    member do
      post :approve
      post :ignore
    end
  end

  match "/groups/archive/:id", :to => "groups#archive", :as => :archive_group, :via => :post
  match "/groups/:id/members", :to => "groups#get_members", :as => :get_members, :via => :get

  resources :motions do
    resources :votes, only: [:new, :edit, :create, :update]
    post :get_and_clear_new_activity, on: :member
    put :close, :on => :member
    put :edit_outcome, :on => :member
    put :edit_close_date, :on => :member
  end

  resources :discussions, except: [:edit] do
    get :activity_counts, on: :collection
    post :update_description, :on => :member
    post :add_comment, :on => :member
    post :show_description_history, :on => :member
    get :new_proposal, :on => :member
    post :edit_title, :on => :member
    put :move, :on => :member
  end

  post "/discussion/:id/preview_version/(:version_id)", :to => "discussions#preview_version", :as => "preview_version_discussion"
  post "/discussion/update_version/:version_id", :to => "discussions#update_version", :as => "update_version_discussion"

  resources :notifications, :only => :index do
    get :groups_tree_dropdown, on: :collection
    get :dropdown_items, on: :collection
    post :mark_as_viewed, :on => :collection, :via => :post
  end


  resources :users, :only => [:new, :create, :update, :show,] do
    put :set_avatar_kind, on: :member
    post :upload_new_avatar, on: :member
  end

  match '/announcements/:id/hide', to: 'announcements#hide', as: 'hide_announcement'

  match "/users/dismiss_system_notice", :to => "users#dismiss_system_notice",
        :as => :dismiss_system_notice_for_user, :via => :post
  match "/users/dismiss_dashboard_notice", :to => "users#dismiss_dashboard_notice",
        :as => :dismiss_dashboard_notice_for_user, :via => :post
  match "/users/dismiss_group_notice", :to => "users#dismiss_group_notice",
        :as => :dismiss_group_notice_for_user, :via => :post
  match "/users/dismiss_discussion_notice", :to => "users#dismiss_discussion_notice",
        :as => :dismiss_discussion_notice_for_user, :via => :post

  resources :comments , only: :destroy do
    post :like, on: :member
    post :unlike, on: :member
  end

  get '/users/invitation/accept' => redirect {|params, request|  "/invitations/#{request.query_string.gsub('invitation_token=','')}"}
  get '/group_requests/:id/start_new_group' => redirect {|params, request|  "/invitations/#{request.query_string.gsub('token=','')}"}

  match "/settings", :to => "users#settings", :as => :user_settings
  match 'email_preferences', :to => "users/email_preferences#edit", :as => :email_preferences, :via => :get
  match 'email_preferences', :to => "users/email_preferences#update", :as => :update_email_preferences, :via => :put

  resources :contributions, only: [:index, :create] do
    get :callback, on: :collection
    get :thanks, on: :collection
  end

  authenticated do
    root :to => 'dashboard#show'
  end

  root :to => 'pages#home'

  scope controller: 'pages' do
    get :about
    get :privacy
    get :browser_not_supported
  end

  scope controller: 'help' do
    get :help
  end

  resources :woc, only: :index do
    post :send_request, on: :collection
  end
  get '/collaborate', to: "woc#index", as: :collaborate

  resources :we_the_people, only: :index do
    post :send_request, on: :collection
  end

  #redirect old invites
  match "/groups/:id/invitations/:token" => "group_requests#start_new_group"

  #redirect old pages:
  get '/pages/how*it*works' => redirect('/about#how-it-works')
  get '/pages/home' => redirect('/')
  get '/get*involved' => redirect('/about#how-it-works')
  get '/how*it*works' => redirect('/about#how-it-works')
  get '/pages/get*involved' => redirect('/about')
  get '/pages/about' => redirect('/about#about-us')
  get '/pages/contact' => redirect('/about#about-us')
  get '/contact' => redirect('/about#about-us')
  get '/pages/privacy' => redirect('/privacy_policy')
end

app/controllers/discussions_controller.rb
class DiscussionsController < GroupBaseController
  inherit_resources
  load_and_authorize_resource :except => [:show, :new, :create, :index, :activity_counts]
  before_filter :authenticate_user!, :except => [:show, :index]
  before_filter :check_group_read_permissions, :only => :show
  after_filter :store_location, :only => :show

  rescue_from ActiveRecord::RecordNotFound do
    render 'application/display_error', locals: { message: t('error.not_found') }
  end

  def new
    @discussion = Discussion.new
    @uses_markdown = current_user.uses_markdown
    if params[:group_id]
      @discussion.group_id = params[:group_id]
    else
      @user_groups = current_user.groups.order('name') unless params[:group_id]
    end
  end

  def create
    current_user.update_attributes(uses_markdown: params[:discussion][:uses_markdown])
    @discussion = current_user.authored_discussions.new(params[:discussion])
    authorize! :create, @discussion
    if @discussion.save
      flash[:success] = t("success.discussion_created")
      redirect_to @discussion
    else
      render action: :new
      flash[:error] = t("error.discussion_not_created")
    end
  end

  def destroy
    @discussion = Discussion.find(params[:id])
    @discussion.delayed_destroy
    flash[:success] = t("success.discussion_deleted")
    redirect_to @discussion.group
  end

  def index
    if params[:group_id].present?
      @group = Group.find(params[:group_id])
      if cannot? :show, @group
        head 401
      else
        @discussions = Queries::VisibleDiscussions.for(@group, current_user).
                       without_current_motions.page(params[:page]).per(10)
        @no_discussions_exist = (@group.discussions.count == 0)
        render :layout => false if request.xhr?
      end
    else
      authenticate_user!
      @discussions = current_user.discussions_sorted.page(params[:page]).per(10)
      @no_discussions_exist = (current_user.discussions.count == 0)
      render :layout => false if request.xhr?
    end
  end

  def show
    @discussion = Discussion.find(params[:id])
    @last_collaborator = User.find @discussion.originator.to_i if @discussion.has_previous_versions?
    @group = GroupDecorator.new(@discussion.group)
    @vote = Vote.new
    @current_motion = @discussion.current_motion
    @activity = @discussion.activity
    @filtered_activity = @discussion.filtered_activity
    assign_meta_data
    if params[:proposal]
      @displayed_motion = Motion.find(params[:proposal])
    elsif @current_motion
      @displayed_motion = @current_motion
    end
    if current_user
      @destination_groups = DiscussionMover.destination_groups(@discussion.group, current_user)
      @uses_markdown = current_user.uses_markdown?
      ViewLogger.motion_viewed(@current_motion, current_user) if @current_motion
      ViewLogger.discussion_viewed(@discussion, current_user)
    end
  end

  def move
    @discussion = Discussion.find(params[:id])
    origin = @discussion.group
    destination = Group.find(params[:discussion][:group_id])
    @discussion.group_id = params[:discussion][:group_id]
    if DiscussionMover.can_move?(current_user, origin, destination) && @discussion.save!
      flash[:success] = "Discussion successfully moved."
    else
      flash[:error] = "Discussion could not be moved."
    end
    redirect_to @discussion
  end

  def add_comment
    if params[:comment].present?
      @discussion = Discussion.find(params[:id])
      @comment = @discussion.add_comment(current_user, params[:comment], params[:uses_markdown])
      current_user.update_attributes(uses_markdown: params[:uses_markdown])
      ViewLogger.discussion_viewed(@discussion, current_user)
      unless request.xhr?
        redirect_to @discussion
      end
    else
      head :ok
    end
  end

  def new_proposal
    discussion = Discussion.find(params[:id])
    if discussion.current_motion
      redirect_to discussion
      flash[:notice] = "A current proposal already exists for this disscussion."
    else
      @motion = Motion.new
      @motion.set_default_close_at_date_and_time
      @motion.discussion = discussion
      @group = GroupDecorator.new(discussion.group)
      render 'motions/new'
    end
  end

  def update_description
    @discussion = Discussion.find(params[:id])
    @discussion.set_description!(params[:description], params[:description_uses_markdown], current_user)
    redirect_to @discussion
  end

  def edit_title
    @discussion = Discussion.find(params[:id])
    @discussion.set_title!(params[:title], current_user)
    redirect_to @discussion
  end

  def show_description_history
    @discussion = Discussion.find(params[:id])
    @originator = User.find @discussion.originator.to_i
    respond_to do |format|
      format.js
    end
  end

  def preview_version
    # assign live item if no version_id is passed
    if params[:version_id].nil?
      @discussion = Discussion.find(params[:id])
    else
      version = Version.find(params[:version_id])
      @discussion = version.reify
    end
    @originator = User.find @discussion.originator.to_i
    respond_to do |format|
      format.js { render :action => 'show_description_history' }
    end
  end

  def update_version
    @version = Version.find(params[:version_id])
    @version.reify.save!
    redirect_to @version.reify()
  end

  def activity_counts
    # this ensures that you can't ask for comment counts for discussions you dont belong to 
    discussion_ids = current_user.discussion_ids & params[:discussion_ids].split('x').map(&:to_i)

    counts = Discussion.find(discussion_ids).map do |discussion|
      discussion.number_of_comments_since_last_looked(current_user)
    end
    render json: counts
  end

  private

  def assign_meta_data
    if @group.viewable_by == :everyone
      @meta_title = @discussion.title
      @meta_description = @discussion.description
    end
  end

  def group
    @group ||= find_group
  end

  def find_group
    if (params[:id] && (params[:id] != "new"))
      Discussion.find(params[:id]).group
    elsif params[:discussion][:group_id]
      Group.find(params[:discussion][:group_id])
    end
  end
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
  include Twitter::Extractor
  include Twitter::Autolink
  def discussion_activity_count_for(discussion, user)
    discussion.number_of_comments_since_last_looked(user)
  end

  def enabled_icon_class_for(discussion, user)
    if discussion_activity_count_for(discussion, user) > 0
      "enabled-icon"
    else
      "disabled-icon"
    end
  end

  def css_class_unread_discussion_activity_for(page_group, discussion, user)
    css_class = "discussion-preview"
    css_class += " showing-group" if (not discussion.group.parent.nil?) && (page_group && (page_group.parent.nil?))
    css_class += " unread" if discussion.number_of_comments_since_last_looked(user) > 0 || discussion.never_read_by(user)
    css_class
  end

  def css_class_for_close_at(motion)
    css_class = "popover-close-date label"

    if motion.close_at
      hours_left = (((Time.now - motion.close_at) / 60) / 60) * -1
      css_class += " color-urgent" if hours_left < 30
      css_class += " color-warning" if (hours_left >= 3) && (hours_left <= 24)
      css_class += " color-ok" if hours_left > 24
    end
    css_class
  end

  def add_mention_links(comment)
    auto_link_usernames_or_lists(comment, :username_url_base => "#", :username_include_symbol => true)
  end

  def css_for_markdown_link(target, setting)
    return "icon-ok" if (target.uses_markdown == setting)
  end

  def markdown_img(uses_markdown)
    if uses_markdown
      image_tag("markdown_on.png", class: 'markdown-icon markdown-on')
    else
      image_tag("markdown_off.png", class: 'markdown-icon markdown-off')
    end
  end
end

app/views/discussions/_activity.html.haml
.divider
%ul#activity-list
  - if discussion.filtered_activity.count == 0
    %li.selector-item.empty-list-message= t :empty_discussion_list
  - else
    - discussion.filtered_activity.each do |event|
      - if event.kind == 'new_comment'
        %li.activity-item-container= render event.eventable
      - else
        - discussion_item = DiscussionItem.new(event)
        %li.activity-item-container= render 'discussion_item', :item => discussion_item

app/views/discussions/_add_comment.html.haml
- if can? :add_comment, discussion
  = form_tag add_comment_discussion_path(discussion), :remote => true, id: "new-comment-form" do
    = render 'avatar', user: current_user, size: "medium", kind: nil, id: nil
    #comment-input{ data: {group: @group.id} }
      = text_area_tag 'comment', "", id: 'new-comment', placeholder: t(:comment_form_placeholder)
      = hidden_field_tag 'uses_markdown', @uses_markdown, {id: 'global-uses-markdown'}
      = submit_tag t(:comment_form_submit_button), class: "btn btn-small submit", id: 'post-new-comment', :data => {:disable_with => t(:comment_form_submit_button)}
    .dropdown#comment-markdown-dropdown.global-markdown-setting
      %a.dropdown-toggle{href:'#comment-markdown-dropdown', id:'comment-markdown-dropdown-link', 'data-toggle'=> 'dropdown'}
        = markdown_img(@uses_markdown)
      = render 'markdown_setting', target: current_user

app/views/discussions/_description.html.haml
.description-container
  .description-body
    .long-description
      = render_rich_text(description, description_markdown_setting)

    - if can? :update_description, discussion
      = link_to t(:edit_discussion_context), "#", class: "edit-description edit-discussion-description bottom-panel-link", id: 'edit_description'

  - if can? :update_description, discussion
    = form_tag update_description_discussion_path(discussion), :id => "description-edit-form", :class => "hidden" do |f|
      = hidden_field_tag 'id'
      = hidden_field_tag 'description_uses_markdown', description_markdown_setting, {id: 'description-markdown-setting'}
      .control-group
        = text_area_tag 'description', description, {id: 'description-input',  :autofocus => true }
      .save-buttons.clearfix
        = submit_tag t(:save), class: 'btn btn-small btn-grey run-validations', id: 'add-description-submit', :data => {:disable_with => t(:saving)}
        = link_to t(:cancel), "#", id: 'cancel-add-description'
        .dropdown#discussion-markdown-dropdown.local-markdown-setting
          %a.dropdown-toggle{href:'#discussion-markdown-dropdown', id:'discussion-markdown-dropdown-link', 'data-toggle'=> 'dropdown'}
            = markdown_img(description_markdown_setting)
          = render 'markdown_setting', target: discussion

app/views/discussions/_description_history.html.haml
.modal-header
  %button.close{"data-dismiss" => "modal"}×
  %h2= t "description_history.header"
.modal-body
  .revision-title
    %h3= @discussion.title
    %p
      = t("description_history.edited_by", when: time_ago_in_words(@discussion.last_versioned_at), who: @originator.name)
      %em
        = " "
        -if @discussion.live?
          =t "description_history.current"
        -else
          =link_to t("description_history.restore"), update_version_discussion_path(@discussion.version), :method => :post, :class => "", :id => "revert-to-version", :data => { :disable_with => t("description_history.applying_changes") }
  .revision-version
    %h3= t "description_history.subheader"
    %p
      -if @discussion.has_previous_versions?
        =link_to t("description_history.previous"), preview_version_discussion_path(@discussion, @discussion.previous_version.version), :method => :post, :id => "discussion-previous-version", :remote => true
      -else
        =link_to t("description_history.previous"), "#", :class => "disabled"
      =" | "
      -if @discussion.next_version.present?
        =link_to t("description_history.next"), preview_version_discussion_path(@discussion, @discussion.next_version.version), :method => :post, :id => "discussion-next-version", :remote => true
      -elsif !(@discussion.live?)
        =link_to t("description_history.next"), preview_version_discussion_path(@discussion), :method => :post, :remote => true
      -else
        =link_to t("description_history.next"), "#", :class => "disabled"
  .revision-content
    %p= render_rich_text(@discussion.description, @discussion.uses_markdown)
.modal-footer
  = link_to t(:close), "#", "data-dismiss" => "modal", class: "btn btn-small btn-grey"

app/views/discussions/_discussion_context.html.haml
.row
  .span8
    =render 'description', discussion: @discussion, description: @discussion.description, description_markdown_setting: @discussion.uses_markdown
  .span3.right-context
    .helper-text.discussion-description-helper-text.hidden
      =render "application/hint", text: t(:"hint.context"), anchor: 'starting-an-engaging-discussion'

    .discussion-additional-info
      = t("discussion_context.started_html",
          when: time_ago_in_words(@discussion.created_at),
          who: @discussion.author.name,
          link: user_path(@discussion.author),
          link_class: 'user-name')
      -if defined? @last_collaborator
        .last-edited-by
          = t("discussion_context.last_edited_html",
              when: time_ago_in_words(@discussion.last_versioned_at),
              who: @last_collaborator.name,
              link: user_path(@last_collaborator),
              link_class: 'user-name')
        .see-revision-history
          %i.icon-time
          =link_to t("discussion_context.see_revision_history"), show_description_history_discussion_path(@discussion), :method => :post, :class => "see-description-history", :remote => true
#description-revision-history.modal.hidden

app/views/discussions/_discussion_item.html.haml
.activity-item-body
  %div{:class => "activity-icon " + item.icon }
  %span.activity-item-actor
    - unless item.actor.blank?
      =link_to item.actor.name, user_path(item.actor), class: "user-name"
  %span.activity-item-header= item.header
  %span.activity-item-content.word-break= item.body
  .activity-item-time= t(:ago, :quantity_of_time => time_ago_in_words(item.time))

app/views/discussions/_discussion_preview.html.haml
.clearfix
  %div{ class: css_class_unread_discussion_activity_for(this_group, discussion, current_user), id: "discussion-preview-#{discussion.id}" }
    %a.selector-discussion-link{ href: discussion_path(discussion) }
      - if user_signed_in? && discussion.current_motion
        .vote-icon
          - if current_user.group_membership(this_group) || this_group.nil?
            %div{:class => 'activity-icon ' + vote_icon_name(current_user.position(discussion.current_motion))}
      .discussion-title
        = truncate(discussion.title, :length => 60, :separator => ' ')
        .group-name= DiscussionDecorator.new(discussion).display_group_name(this_group)
      .large-icon.discussion-icon.activity-icon{ class: enabled_icon_class_for(discussion, current_user) }
        - discussion_activity = discussion_activity_count_for(discussion, current_user)
        - if discussion_activity > 0
          %span.activity-count.label.label-info
            = discussion_activity
      .discussion-date-info
        -if discussion.current_motion
          - if discussion.current_motion_close_at
            .proposal-close-date= "#{time_ago_in_words(discussion.current_motion_close_at)} until close"
        - else
          .latest-comment-time= "#{t('ago', :quantity_of_time => time_ago_in_words(discussion.latest_comment_time))}"
    - if discussion.current_motion
      - motion_activity = motion_activity_count_for(discussion.current_motion, current_user)
      - popover_title = render 'discussions/graph_preview_pop_over_title', :motion => discussion.current_motion
      - popover_content = render 'discussions/graph_preview_pop_over', :motion => discussion.current_motion, :user => current_user, :motion_activity =>  motion_activity
      .motion-popover-link{id: "popover_#{discussion.current_motion.id}", 'data-title' => popover_title, 'data-content' => popover_content}
        .pie{:id => "graph_#{discussion.current_motion.id}"}
          - if discussion.current_motion.voting? && motion_activity > 0
            %span.activity-count.label.label-info
              = motion_activity
          - if user_signed_in?
            = button_to '', get_and_clear_new_activity_motion_path(:id => discussion.current_motion.id, :motion_activity => motion_activity), :remote => true, :class =>  "preview-pie-button"
    - else
      .large-icon.pie-icon.activity-icon

- if discussion.current_motion
  :coffeescript
    $ ->
      # Display vote graph
      make_the_graph = ->
        @pie_graph_view = new Loomio.Views.Utils.GraphView
          el: '.pie'
          id_string: "graph_#{discussion.current_motion.id}"
          legend: false
          data: #{discussion.current_motion.votes_for_graph.to_json.html_safe}
          type: 'pie'
          tooltip_selector: '#tooltip'
          diameter: 25
          padding: 1
          gap: 1
          shadow: 0

      # IE8 FIX - for some reason we have to load the graph after everything else.
      # Otherwise, the graph doesn't display in IE8.
      #
      # Ideally, we'd like to be able to delete this line:
      $(window).load(make_the_graph)

app/views/discussions/_graph_preview_pop_over.html.haml
- if user_signed_in? && user.is_group_member?(motion.group)
  %span.popover-current-position
    = "Your position"
    %div{:class => 'activity-icon ' + vote_icon_name(user.get_position_for(motion))}

.popover-engagement
  = t(:participation) + " #{motion.percent_voted}%"

- if motion_activity > 0
  .popover-header
    =t :new_activity
  %ul.popover-activity-list
    - motion.votes.order('created_at DESC')[(0..motion_activity - 1)].each do |vote|
      %li.popover-item
        = render "discussions/graph_preview_pop_over_votes", vote: vote, motion: motion

app/views/discussions/_graph_preview_pop_over_votes.html.haml
= render 'avatar', user: vote.user, size: "medium", kind: nil, id: nil
%div{:class => 'activity-icon ' + vote_icon_name(vote.position)}
%strong= vote.user.name 
- if vote.statement != ""
  = " - " 
  = vote.statement
.vote-time
  = t(:ago, :quantity_of_time => time_ago_in_words(vote.created_at))

app/views/discussions/_options.html.haml
.dropdown#discussion-options
  = link_to image_tag("dropdown.png"), "#", id: "options-dropdown", class: "dropdown-toggle", 'data-toggle' => 'dropdown'
  %ul.dropdown-menu.pull-right
    - if can?(:edit_title, discussion)
      %li= link_to t(:edit_discussion_title), "#", :id => "edit-title"
    - unless @destination_groups.blank?
      %li= link_to "Move discussion", '#move-discussion-modal', "data-toggle" => "modal", id: 'move-discussion'
    -if can? :destroy, discussion
      %li= link_to t(:delete_discussion), "#", 'data-method-type' => 'delete', 'data-title' => t(:delete_discussion), 'data-body' => t(:confirm_delete_discussion), 'data-confirm-path' => discussion_path(discussion), class: 'confirm-dialog', id: 'delete-discussion'

#move-discussion-modal.modal.hidden
  .modal-header
    %button.close{"data-dismiss" => "modal"}×
    %h3= "Where would you like to move this discussion to?"
  = simple_form_for discussion, url: move_discussion_path(discussion), method: :put do |f|
    .modal-body
      = f.input :group_id, collection: @destination_groups, include_blank: false, label: false, id: "destination_groups"
    .modal-footer
      = f.button :submit, "Move discussion", class: "btn btn-danger", id: 'move-discussion-submit', :data => { :disable_with => "Move discussion" }
      = link_to "Cancel", "#", "data-dismiss" => "modal", class: "btn"

app/views/discussions/add_comment.js.erb
$("#new-comment").val('');
$("ul#activity-list").prepend("<li class='activity-item-container'><%=escape_javascript(render @comment)%></li>");

app/views/discussions/new.html.haml
.page-container
  - group = GroupDecorator.decorate(@discussion.group) if @discussion.group
  = render '/groups/title', group: group
  = render "/discussions/form", :discussion => @discussion, :user_groups => @user_groups

app/views/discussions/show.html.haml
- set_title @group.name, @discussion.title, @group.parent
=render '/groups/title', group: @group
.row
  .span12
    .selector-panel
      = render 'title', discussion: @discussion
      #discussion-content-container
        #discussion-context= render 'discussion_context'
        .row
          .span6#content-comments
            .large-icon.discussion-icon.enabled-icon
            %h3.header-text= t :discussion
            #discussion-activity-body
              = render 'add_comment', discussion: @discussion
              #activity-feed
                = render 'activity', discussion: @discussion

          .span6#content-proposal
            .large-icon.decision-icon
            %h3.header-text= t :current_decision
            .content-proposal-body
              %ul.selector-list
                - if @current_motion.nil?
                  - if can? :create, Motion.new(discussion_id: @discussion.id)
                    = link_to t(:create_new_proposal), new_proposal_discussion_path(@discussion.id), class: 'btn new-proposal-btn', id: 'new-proposal'
                    %li.selector-item.empty-list-message#start-proposal-text
                      = t :empty_decision_list_html
                - else
                  - if @displayed_motion == @current_motion
                    - if can? :close_voting, @current_motion
                      %li= render '/motions/admin_buttons', :motion => @current_motion
                    %li.selector-item.current-proposal
                      = render @current_motion, unique_votes: @current_motion.unique_votes
                  - else
                    %li.selector-item.current-proposal
                      = render '/motions/motion_preview', motion: @current_motion, this_group: @group

            - if can? :edit_close_date, @current_motion
              = render '/motions/edit_close_date', motion: @current_motion, user: @current_user, input_time: @input_time

            - if @discussion.closed_motions.count > 0
              #previous-proposals
                .clearfix
                  .large-icon.decision-icon
                  %h3.header-text= t :previous_decisions
                .content-proposal-body
                  %ul.selector-list
                    - @discussion.closed_motions.each do |closed_motion|
                      - if closed_motion == @displayed_motion
                        %li.selector-item= render closed_motion, unique_votes: closed_motion.unique_votes, this_group: @group
                      - else
                        %li.selector-item= render '/motions/motion_preview', motion: closed_motion, this_group: @group

/ - if user_signed_in?#  && (not current_user.has_read_discussion_notice)
/   = render "application/help_text", header: t("discussion_helper_text.header"), message: t("discussion_helper_text.message").html_safe, path: dismiss_discussion_notice_for_user_path

app/views/discussions/show_description_history.js.erb
var modal = $("#description-revision-history")

if(modal.is(":hidden")){
  modal.modal
  modal.modal('show')
}

modal.html("<%= escape_javascript(render 'description_history')%>")
modal.find("a.disabled").bind('click', false)