config/routes.rb
Loomio::Application.routes.draw do

  get "/groups", to: 'groups/public_groups#index', as: :public_groups

  ActiveAdmin.routes(self)

  devise_for :users, controllers: { sessions: 'users/sessions',
                                    registrations: 'users/registrations' }

  get "/inbox", to: "inbox#index", as: :inbox
  get '/inbox/preferences', to: 'inbox#preferences', as: :inbox_preferences
  put '/inbox/update_preferences', to: 'inbox#update_preferences', as: :update_inbox_preferences
  match '/inbox/mark_as_read', to: 'inbox#mark_as_read', as: :mark_as_read_inbox
  match '/inbox/mark_all_as_read', to: 'inbox#mark_all_as_read', as: :mark_all_as_read_inbox
  match '/inbox/unfollow', to: 'inbox#unfollow', as: :unfollow_inbox


  resources :invitations, only: [:show]

  resources :group_requests, only: [:create, :new] do
    get :verify, on: :member
  end

  match "/request_new_group", to: "group_requests#new", as: :request_new_group

  match "/group_request_confirmation", to: "group_requests#confirmation", as: :group_request_confirmation

  resources :groups, except: [:index, :new] do
    resources :invitations, only: [:index, :destroy, :new, :create], controller: 'groups/invitations'
    resources :memberships, only: [:index, :destroy, :new, :create], controller: 'groups/memberships' do
      member do
       post :make_admin
       post :remove_admin
      end
    end

    get :setup, on: :member, to: 'groups/group_setup#setup'
    put :finish, on: :member, to: 'groups/group_setup#finish'

    post :add_members, on: :member
    post :hide_next_steps, on: :member
    get :add_subgroup, on: :member

    resources :motions
    resources :discussions, only: [:index, :new]
    post :email_members, on: :member
    post :edit_description, on: :member
    post :edit_privacy, on: :member
    delete :leave_group, on: :member
  end

  get 'groups/:group_id/request_membership',   to: 'groups/membership_requests#new',          as: :new_group_membership_request
  post 'groups/:group_id/membership_requests', to: 'groups/membership_requests#create',       as: :group_membership_requests
  delete 'membership_requests/:id/cancel',     to: 'groups/membership_requests#cancel',       as: :cancel_membership_request

  get 'groups/:group_id/membership_requests',  to: 'groups/manage_membership_requests#index', as: :group_membership_requests
  resources :membership_requests, only: [], controller: 'groups/manage_membership_requests' do
    member do
      post :approve
      post :ignore
    end
  end

  match "/groups/archive/:id", :to => "groups#archive", :as => :archive_group, :via => :post
  match "/groups/:id/members", :to => "groups#get_members", :as => :get_members, :via => :get

  resources :motions do
    resources :votes, only: [:new, :edit, :create, :update]
    post :get_and_clear_new_activity, on: :member
    put :close, :on => :member
    put :edit_outcome, :on => :member
    put :edit_close_date, :on => :member
  end

  resources :discussions, except: [:edit] do
    get :activity_counts, on: :collection
    post :update_description, :on => :member
    post :add_comment, :on => :member
    post :show_description_history, :on => :member
    get :new_proposal, :on => :member
    post :edit_title, :on => :member
    put :move, :on => :member
  end

  post "/discussion/:id/preview_version/(:version_id)", :to => "discussions#preview_version", :as => "preview_version_discussion"
  post "/discussion/update_version/:version_id", :to => "discussions#update_version", :as => "update_version_discussion"

  resources :notifications, :only => :index do
    get :groups_tree_dropdown, on: :collection
    get :dropdown_items, on: :collection
    post :mark_as_viewed, :on => :collection, :via => :post
  end


  resources :users, :only => [:new, :create, :update, :show,] do
    put :set_avatar_kind, on: :member
    post :upload_new_avatar, on: :member
  end

  match '/announcements/:id/hide', to: 'announcements#hide', as: 'hide_announcement'

  match "/users/dismiss_system_notice", :to => "users#dismiss_system_notice",
        :as => :dismiss_system_notice_for_user, :via => :post
  match "/users/dismiss_dashboard_notice", :to => "users#dismiss_dashboard_notice",
        :as => :dismiss_dashboard_notice_for_user, :via => :post
  match "/users/dismiss_group_notice", :to => "users#dismiss_group_notice",
        :as => :dismiss_group_notice_for_user, :via => :post
  match "/users/dismiss_discussion_notice", :to => "users#dismiss_discussion_notice",
        :as => :dismiss_discussion_notice_for_user, :via => :post

  resources :comments , only: :destroy do
    post :like, on: :member
    post :unlike, on: :member
  end

  get '/users/invitation/accept' => redirect {|params, request|  "/invitations/#{request.query_string.gsub('invitation_token=','')}"}
  get '/group_requests/:id/start_new_group' => redirect {|params, request|  "/invitations/#{request.query_string.gsub('token=','')}"}

  match "/settings", :to => "users#settings", :as => :user_settings
  match 'email_preferences', :to => "users/email_preferences#edit", :as => :email_preferences, :via => :get
  match 'email_preferences', :to => "users/email_preferences#update", :as => :update_email_preferences, :via => :put

  resources :contributions, only: [:index, :create] do
    get :callback, on: :collection
    get :thanks, on: :collection
  end

  authenticated do
    root :to => 'dashboard#show'
  end

  root :to => 'pages#home'

  scope controller: 'pages' do
    get :about
    get :privacy
    get :browser_not_supported
  end

  scope controller: 'help' do
    get :help
  end

  resources :woc, only: :index do
    post :send_request, on: :collection
  end
  get '/collaborate', to: "woc#index", as: :collaborate

  resources :we_the_people, only: :index do
    post :send_request, on: :collection
  end

  #redirect old invites
  match "/groups/:id/invitations/:token" => "group_requests#start_new_group"

  #redirect old pages:
  get '/pages/how*it*works' => redirect('/about#how-it-works')
  get '/pages/home' => redirect('/')
  get '/get*involved' => redirect('/about#how-it-works')
  get '/how*it*works' => redirect('/about#how-it-works')
  get '/pages/get*involved' => redirect('/about')
  get '/pages/about' => redirect('/about#about-us')
  get '/pages/contact' => redirect('/about#about-us')
  get '/contact' => redirect('/about#about-us')
  get '/pages/privacy' => redirect('/privacy_policy')
end

app/controllers/groups/group_setup_controller.rb
class Groups::GroupSetupController < GroupBaseController

  before_filter :require_current_user_is_group_admin
  before_filter :redirect_to_group_if_already_setup


  def setup
  end

  def finish
    if @group.update_attributes(params[:group])
      @group.update_attribute(:setup_completed_at, Time.now)
      SetupGroup.create_example_discussion(@group)
      redirect_to @group
    else
      render 'setup'
    end
  end

  private

  def redirect_to_group_if_already_setup
    if @group.is_setup?
      flash[:warning] = t("error.group_already_setup")
      redirect_to @group
    end
  end
end

app/controllers/groups/invitations_controller.rb
class Groups::InvitationsController < GroupBaseController
  before_filter :require_current_user_can_invite_people
  before_filter :ensure_invitations_available, only: [:new, :create]

  def new
    @invite_people = InvitePeople.new
    load_decorated_group
  end

  def create
    @invite_people = InvitePeople.new(params[:invite_people])
    if @invite_people.valid?
      num = CreateInvitation.to_people_and_email_them(@invite_people, group: @group, inviter: current_user)
      flash[:notice] = "#{num} invitation(s) sent" if num > 0
      redirect_to group_path(@group)
    else
      load_decorated_group
      render :new
    end
  end

  def index
    @pending_invitations = @group.pending_invitations
    load_decorated_group
  end

  def destroy
    load_invitation
    @invitation.cancel!(canceller: current_user)
    redirect_to group_invitations_path(@group), notice: "Invitation to #{@invitation.recipient_email} cancelled"
  end

  private

  def ensure_invitations_available
    unless @group.invitations_remaining > 0
      render 'no_invitations_left'
    end
  end

  def load_invitation
    @invitation = @group.pending_invitations.find(params[:id])
  end

  def load_decorated_group
    @group = GroupDecorator.new(Group.find(params[:group_id]))
  end
end

app/controllers/groups/manage_membership_requests_controller.rb
class Groups::ManageMembershipRequestsController < GroupBaseController
  load_and_authorize_resource :membership_request, only: [:approve, :ignore], parent: false
  before_filter :load_group_and_check_for_response, only: [:approve, :ignore]

  def index
    @group = GroupDecorator.new Group.find(params[:group_id])
    if can? :manage_membership_requests, @group
      render 'index'
    else
      redirect_to group_path(@group)
      flash[:warning] = t(:'error.access_denied')
    end
  end

  def approve
    ManageMembershipRequests.approve!(@membership_request, approved_by: current_user)
    set_request_approved_flash_message
    redirect_to group_membership_requests_path(@group)
  end

  def ignore
    ManageMembershipRequests.ignore!(@membership_request, ignored_by: current_user)
    flash[:success] = t(:'notice.membership_request_ignored')
    redirect_to group_membership_requests_path(@group)
  end

  private

  def load_group_and_check_for_response
    @group = @membership_request.group
    response = @membership_request.response
    unless response.nil?
      if response == 'approved'
        flash[:warning] = t(:'warning.membership_request_already_approved')
      elsif response == 'ignored'
        flash[:warning] = t(:'warning.membership_request_already_ignored')
      end
      redirect_to group_membership_requests_path(@group)
    end
  end

  def set_request_approved_flash_message
    if @membership_request.from_a_visitor?
      flash[:success] = t(:'notice.membership_approved')+ ' ' +  t(:'notice.new_user_added', user_email_or_name: @membership_request.name)
    else
      flash[:success] = t(:'notice.membership_approved')+ ' ' + t(:'notice.user_added', user_email_or_name: @membership_request.name)
    end
  end
end

app/controllers/groups/membership_requests_controller.rb
class Groups::MembershipRequestsController < BaseController
  before_filter :load_group, except: [:new, :cancel]
  before_filter :authenticate_user!, except: [:new, :create, :cancel]
  load_and_authorize_resource :membership_request, only: :cancel, parent: false


  def new
    @group = GroupDecorator.new Group.find(params[:group_id])
    @membership_request = MembershipRequest.new
    @membership_request.group = @group
    @membership_request.requestor = current_user
    authorize! :create, @membership_request
  end

  def create
    build_membership_request
    authorize! :create, @membership_request
    if @membership_request.save
      flash[:success] = t(:'success.membership_requested')
      Events::MembershipRequested.publish!(@membership_request)
      redirect_to @group
    else
      if @membership_request.errors[:requestor].any?
        flash[:warning] = @membership_request.errors[:requestor].first
        redirect_to @group
      else
        render 'new'
      end
    end
  end

  def cancel
    @membership_request.destroy
    flash[:success] = t(:'notice.membership_request_canceled')
    redirect_to @membership_request.group
  end

  private

  def load_group
    @group ||= GroupDecorator.new Group.find(params[:group_id])
  end

  def build_membership_request
    @membership_request = MembershipRequest.new params[:membership_request]
    @membership_request.group = @group
    @membership_request.requestor = current_user if user_signed_in?
  end
end

app/controllers/groups/memberships_controller.rb
class Groups::MembershipsController < GroupBaseController
  load_and_authorize_resource :except => [:destroy, :index]
  before_filter :require_current_user_is_group_admin, only: [:make_admin, :remove_admin, :index]
  before_filter :load_membership, only: [:make_admin, :remove_admin]

  # membership actions
  def index
    @memberships = @group.memberships
    @group = GroupDecorator.new(Group.find(params[:group_id]))
  end

  def make_admin
    if @membership.member?
      @membership.make_admin!
      flash[:notice] = t("notice.user_made_admin", which_user: @membership.user_name)
    else
      flash[:warning] = t("warning.user_already_admin", which_user: @membership.user_name)
    end
    redirect_to [@group, :memberships]
  end

  def remove_admin
    if @membership.admin?
      if @membership.group_has_multiple_admins?
        @membership.remove_admin!
        flash[:notice] = t("notice.admin_rights_removed", which_user: @membership.user_name)
      else
        flash[:warning] = t("warning.cant_remove_last_admin")
      end
    else
      flash[:warning] = t("warning.user_not_admin", which_user: @membership.user_name)
    end
    redirect_to [@group, :memberships]
  end

  def destroy
    if @membership = Membership.find_by_id(params[:id])
      authorize! :destroy, @membership
      @membership.destroy
      if current_user == @membership.user
        flash[:notice] = t("notice.you_have_left_group", which_group: @membership.group.name)
      else
        flash[:notice] = t("notice.member_removed")
      end
      redirect_to group_memberships_path(@membership.group)
    else
      redirect_to :back
    end
  end

end

app/controllers/groups/public_groups_controller.rb
class Groups::PublicGroupsController < BaseController
  before_filter :authenticate_user!, except: [:index]

  def index
    if params[:query]
      @groups = Group.visible_to_the_public.
                search_full_name(params[:query]).
                page(params[:page])
    else
      @groups = Group.visible_to_the_public.page(params[:page])
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
  def css_for_privacy_link(group, link)
    current_privacy_setting = String(group.viewable_by)
    return "icon-ok" if link == current_privacy_setting
  end

  def display_subgroups_block?(group)
    group.parent.nil? && (group.subgroups.present? || (current_user && group.users_include?(current_user)))
  end

  def logged_in_member_can_invite?(group)
    user_signed_in? && current_user.is_group_member?(group) && group.members_can_invite?
  end

  def show_next_steps?(group)
    user_signed_in? && current_user.is_group_admin?(group) && !group.next_steps_completed? && @group.is_top_level?
  end

  def pending_membership_requests_count(group)
    if group.pending_membership_requests.count > 0
      t(:number_pending, pending: group.pending_membership_requests.count)
    else
      ""
    end
  end

  def members_pending_count(group)
    if group.pending_invitations.count > 0
      t(:and_number_pending, pending: group.pending_invitations.count)
    else
      ""
    end
  end

  # sorry, not gonna bother refactoring this right now (Jon)
  def request_membership_button(group)
    if visitor?
      if group.is_a_parent?
        request_membership_icon_button(group)
      else
        disabled_request_membership_button(group)
      end
    else
      return if group.users_include?(current_user)
      membership_request = group.membership_requests.where(requestor_id: current_user.id, response: nil).first
      if membership_request.present?
        cancel_membership_request_button(membership_request)
      else
        if group.is_a_parent?
          request_membership_icon_button(group)
        else
          if group.user_is_a_parent_member?(current_user)
            request_membership_icon_button(group)
          else
            disabled_request_membership_button(group)
          end
        end
      end
    end
  end

  def disabled_request_membership_button(group)
    request_membership_icon_button(group, href: "#", class: "btn-info disabled tooltip-top",
                                   id: 'request-membership-disabled',
                                   title: "You must be a member of the parent group before you can join this subgroup.")
  end

  def cancel_membership_request_button(membership_request)
    icon_button(href: cancel_membership_request_path(membership_request),
                method: 'delete',
                text: t(:cancel_membership_request),
                icon: '/assets/group-dark.png',
                id: 'membership-requested',
                class: 'btn-grey',
                'data-confirm' => t(:confirm_remove_membership_request))
  end

  def request_membership_icon_button(group, params={})
    old_params = { href: new_group_membership_request_path(group),
                   text: t(:request_membership),
                   icon: '/assets/group.png',
                   id: 'request-membership',
                   class: 'btn-info' }
    new_params = old_params.merge(params)
    icon_button(new_params)
  end
end

app/views/groups/_email_members.html.haml
.modal-header
  %button.close{"data-dismiss" => "modal"}×
  %h3= t :email_members_in_group, which_group: group.full_name
= form_tag email_members_group_path(group) do
  .modal-body
    .control-group
      = label_tag "group_email_subject", t(:subject)
      %span.presence-error-message= t :subject_error
      = text_field_tag "group_email_subject", nil, :placeholder => t(:subject_placeholder), :class => "validate-presence"
    .control-group
      = label_tag "group_email_body", t(:message)
      %span.presence-error-message= t :message_error
      = text_area_tag "group_email_body", nil, :placeholder => t(:message_placeholder, which_group: group.full_name), :class => "validate-presence"
  .modal-footer
    = submit_tag t(:send_email), class: "btn btn-info run-validations", :data => { :disable_with => t(:send_email) }

app/views/groups/_group_admin_panel.html.haml
.sub-panel#group-admin-panel
  %h4 Admin
  %ul
    %li=link_to 'Edit memberships', group_memberships_path(group)
    %li=link_to 'Pending invitations', group_invitations_path(group)

app/views/groups/_invite_users.html.haml
%h1= t("invitation.invite_people")
%br
.control-group
  %p= t("invitation.recipients")
  = text_area_tag 'invitees', nil, class: 'validate-emails', placeholder: t("invitation.invitees_placeholder")
  .email-validation-help= t('error.invalid_email')
  %br
  %br
  = form.input :recipients, as: :hidden, input_html: { class: 'recipients' }
.control-group
  = form.input :message_body, label: false, as: :text, input_html: { value: t("invitation.body_editable", group: group.name) }, label: t("invitation.message_body")

app/views/groups/_members.html.haml
- unless group.hide_members && (cannot? :update, group)
  .sub-panel#members-panel
    -if can?(:update, group) or logged_in_member_can_invite?(group)
      .dropdown.btn-group
        %a.btn.btn-grey.btn-small.dropdown-toggle#group-member-options{ href: "#", 'data-toggle' => 'dropdown' }
          = t(:options)
        %ul.dropdown-menu.pull-right.group-member-options
          -if can? :add_members, group
            -if group.is_top_level?
              %li=link_to t(:invite_people), new_group_invitation_path(group)
            -else
              %li=link_to t(:add_new_member), '#invite-subgroup-members', :id => 'group-add-members', 'data-toggle' => 'modal'
          -if can? :edit, group
            %li=link_to t(:edit_memberships), group_memberships_path(group)
          - if can? :email_members, group
            %li= link_to t(:email_group_members), "#email-members-modal", "data-toggle" => "modal"
    -if group.is_sub_group?
      #invite-subgroup-members.modal.hidden
        = render 'subgroup_add_members', group: group
    %h4
      = "#{ t :members } (#{ group.memberships_count })"

    %ul#users-list
      - group.users.sorted_by_name.each do |user|
        = render 'membership', user: user, group: group
    -if can?(:add_members, group) && group.is_top_level?
      = link_to members_pending_count(group), group_invitations_path(group), class: 'bottom-panel-link', id: 'pending-count'

app/views/groups/_membership.html.haml
%li{:id => user.id}
  = render 'avatar', user: user, size: "small", kind: nil, id: nil
  .user-name
    %span.membership-user-name
      = link_to user.name, user_path(user), class: 'user-name'

app/views/groups/_membership_request.html.haml
%li
  .membership-user-name= truncate(membership_request.name, :length => 29, :omission => '...')
  =link_to t(:approve), "#", 'data-title' => t(:approve), 'data-body' => t(:confirm_approve_membership_request, which_user: membership_request.name), 'data-confirm-path' => approve_membership_request_path(membership_request), 'data-method-type' => 'post', class: 'confirm-dialog', id: 'approve'
  =link_to "×", "#", 'data-title' => t(:ignore_request), 'data-body' => t(:confirm_ignore_membership_request, which_user: membership_request.name), 'data-confirm-path' => ignore_membership_request_path(membership_request), 'data-method-type' => 'post', class: 'confirm-dialog close', id: 'ignore'

app/views/groups/_options_dropdown.html.haml
- if params[:controller] == 'groups' && params[:action] == 'show'
  - can_edit = can? :edit, group
  - can_leave = group.users_include? current_user
  - can_archive = can? :edit, group
  - can_email = can? :email_members, group
  - if can_edit || can_leave
    .dropdown.group-options
      = icon_button(href: '#', text: t(:options), icon: '/assets/options-cog.png', id: 'group-options', class: 'btn-grey dropdown-toggle', 'data-toggle' => 'dropdown')
      %ul.dropdown-menu.pull-right
        - if can_edit
          %li= link_to t(:edit_group_settings), edit_group_path(group)
        - if can_leave
          - membership = current_user.group_membership(group)
          %li= link_to t(:leave_group), "#", 'data-title' => t(:leave_group), 'data-body' => t(:confirm_leave_group, which_group: group.name), 'data-confirm-path' => group_membership_path(group, membership), 'data-method-type' => 'delete', class: 'confirm-dialog', id: 'leave group'
        - if can_archive
          %li= link_to t(:deactivate_group), "#", 'data-title' => t(:deactivate_group), 'data-body' => t(:confirm_deactivate_group, which_group: group.name), 'data-confirm-path' => archive_group_path(group), 'data-method-type' => 'post', class: 'confirm-dialog', id: 'de-activate group'
  - if can_email
    #email-members-modal.modal.hidden
      = render "groups/email_members", :group => group

app/views/groups/_setup_next_steps.html.haml
.sub-panel#setup-next-steps
  %h4
    = t :setup_steps_title
    = link_to("×", hide_next_steps_group_path(@group), method: :post, remote: true, class: "close hide-next-steps")
  %ol
    %li#example_discussion= t(:setup_step_1)
    %li#first_discussion= t(:setup_step_2)
    %li#invite_people= t(:setup_step_3)

app/views/groups/edit.html.haml
- set_title @group.name, t(:edit_group)
= render '/groups/title', group: @group
= render 'form', group: @group, parent: @parent, submit_text: t(:update_group), disable_text: t(:updating_group), form_title: t(:edit_group)

app/views/groups/edit_description.js.erb
var description = $("#description-input").val()
$(".long-description").html("<%= j render_rich_text(@description, false) %>")
$(".description-body").show()
$("#description-edit-form").hide()
$(".discussion-description-helper-text").toggle()

app/views/groups/edit_privacy.js.erb
$("#privacy-image").attr('src', "/assets/privicon_<%= @group.viewable_by.to_s %>.png")
tooltipTitle = "Privacy: '<%= @group.viewable_by.to_s %>' can see this group."
$("#privacy").attr('data-original-title', tooltipTitle)
             .tooltip('fixTitle');

app/views/groups/hide_next_steps.js.erb
$('#setup-next-steps').hide();

app/views/groups/new.html.haml
- set_title "", t(:new_group)
.page-container
  = render 'form', group: @group, parent: @parent, submit_text: t(:create_group), disable_text: t(:creating_group), form_title: t(:new_group)

app/views/groups/show.html.haml
.row
  .span9
    - set_title @group.name, "", @group.parent
    = render '/groups/title', group: @group
    - if can? :create, @discussion
      = icon_button(href: new_discussion_path(:group_id => @group.id), text: t(:start_a_discussion), icon: '/assets/topic-18.png', id: 'start-new-discussion', class: 'btn-grey')
  .span3#button-container
    - if can?(:add_members, @group)
      = render 'invite_button', group: @group
    = render 'options_dropdown', group: @group
    = request_membership_button(@group)

.row.main-content
  %section.span9
    %ul.selector-list.bordered
      #all-discussions-loading
        %li.selector-item.loading= t(:loading)
      #discussions-with-motions
        - @discussions.with_current_motions_user_has_not_voted_on.each do |discussion|
          %li.selector-item= render '/discussions/discussion_preview', discussion: discussion, this_group: @group
        - @discussions.with_current_motions_user_has_voted_on.each do |discussion|
          %li.selector-item= render '/discussions/discussion_preview', discussion: discussion, this_group: @group
        .discussion-with-motion-divider.hidden
      #group-discussions.hidden
        %div{ class: "group_#{@group.id}" }

  %section.span3
    =render 'setup_next_steps' if show_next_steps?(@group)
    =render 'groups/description', group: @group
    =render 'subgroups', subgroups: @subgroups, group: @group if display_subgroups_block?(@group)
    =render '/application/see_closed_motions'
    =render 'membership_requests', group: @group
    =render 'members', group: @group
  =render '/application/closed_motions', user: nil, group: @group